package uk.ac.rhul.cs.cl1;

/**
 * Abstract seed nodeset generator class.
 * 
 * A seed nodeset generator is an abstract algorithm that produces a set of candidate
 * seed nodesets from a graph. These candidate nodesets will be passed on to a
 * {@link ClusterGrowthProcess} during a {@link ClusterONEAlgorithm} to produce
 * the clusters.
 * 
 * Seed nodeset generators implement the {@link Iterable} interface, so the easiest
 * way to get the set of seed nodesets is to iterate over it in a for loop.
 *  
 * @author tamas
 */
public abstract class SeedGenerator extends GraphAlgorithm implements Iterable<MutableNodeSet> {
	/**
	 * Constructs a seed generator that is not associated to any graph yet.
	 */
	public SeedGenerator() {
		this(null);
	}

	/**
	 * Constructs a seed generator that is associated to a given graph.
	 * @param graph   the graph the seed generator will operate on
	 */
	public SeedGenerator(Graph graph) {
		super(graph);
	}
	
	/**
	 * Returns the number of seeds that will be generated.
	 * If the number of seeds cannot be known in advance, -1 will be returned.
	 * @return   the expected number of seeds generated by the generator, or -1 if the
	 *           number of seeds is not known in advance.
	 */
	public abstract int size();
	
	/**
	 * Factory method that can construct seed generators from a simple string description.
	 * The following specifiers are recognised at the moment:
	 * <ul>
	 * <li><tt>nodes</tt> - generates a singleton seed for each node of the graph</li>
	 * <li><tt>edges</tt> - generates a seed containing the two endpoints for each edge of the graph</li>
	 * </ul>
	 * 
	 * @param  specification   the specification string
	 * @param  graph           the graph used by the constructed seed generator
	 * @throws InstantiationException if the specification string is invalid
	 */
	public static SeedGenerator fromString(String specification, Graph graph) throws InstantiationException {
		if (specification.equals("nodes"))
			return new EveryNodeSeedGenerator(graph);
		
		if (specification.equals("edges"))
			return new EveryEdgeSeedGenerator(graph);
		
		throw new InstantiationException("unknown seed generator type: "+specification);
	}
	
	/**
	 * Factory method that can construct seed generators from a simple string description.
	 * 
	 * The constructed seed generator will not be associated to any given graph yet.
	 * 
	 * @param  specification   the specification string
	 * @throws InstantiationException if the specification string is invalid
	 */
	public static SeedGenerator fromString(String specification) throws InstantiationException {
		return fromString(specification, null);
	}
}
