package uk.ac.rhul.cs.cl1;

import java.util.Iterator;

/**
 * Iterator that iterates over {@link MutableNodeSet}s.
 * 
 * This class provides an extra feature compared to "plain" iterators:
 * the clustering algorithm will report back to the iterator whenever a
 * cluster is found, and the iterator has the chance to adapt its
 * behaviour if needed. This is used to implement {@link UnusedNodeSeedGenerator}
 * where nodes that are found in a cluster are not generated by the iterator
 * later on.
 * 
 * @author tamas
 */
public abstract class SeedIterator implements Iterator<MutableNodeSet> {
	/**
	 * Method that will be called whenever a cluster is found.
	 * 
	 * This method does nothing by default.
	 */
	public void processFoundCluster(NodeSet cluster) {
	}
}
